name: 'Build and Deploy to Cloud Run (MAIN)'

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'centering-valve-453419-t2'
  REGION: 'asia-southeast1'
  SERVICE: 'doo-doung-frontend'
  GAR_REPOSITORY: 'quickstart-docker-repo-asia'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/227513314381/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
  SERVICE_ACCOUNT: 'github-actions-deployer@centering-valve-453419-t2.iam.gserviceaccount.com'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.SERVICE_ACCOUNT }}'

      - name: 'Configure Docker Authentication'
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: 'Build and Push Docker Image'
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          echo "Building and pushing Docker image: $DOCKER_TAG"
          docker build -t "$DOCKER_TAG" .
          docker push "$DOCKER_TAG"

      - id: deploy
        name: 'Deploy to Cloud Run'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}'

      - name: 'Show output URL'
        run: 'echo "Cloud Run MAIN Service URL: ${{ steps.deploy.outputs.url }}"'